author: [Zhuowei,MinecraftDawn,lasteamlab]
description: Implementation of the Minecraft PI modding API
main: io.github.lasteamlab.mcpythonmod.MCPythonMod
name: MCPythonMod
startup: postworld
version: '1.15-0.0'
api-version: 1.13